### ISSUE TITLE
neither npm nore yarn is working out

### ISSUE THREAD

**Issue by codeistalk** [ant-vel/Installer#6]
```
**$ yarn install**
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/2] ⠐ waiting...
[2/2] ⠐ node-sass: verb could not find "python". checking python launcher
[-/2] ⠈ waiting...
[-/2] ⠈ waiting...
error An unexpected error occurred: "F:\\project\\App-master\
ode_modules\
ode-sass: Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node scripts/build.js
Directory: F:\\project\\App-master\
ode_modules\
ode-sass
Output:
Building: C:\\Program Files\
odejs\
ode.exe F:\\project\\App-master\
ode_modules\
ode-gyp\\bin\
ode-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\\\Program Files\\\
odejs\\\
ode.exe',
gyp verb cli   'F:\\\\project\\\\App-master\\\
ode_modules\\\
ode-gyp\\\\bin\\\
ode-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\\project\\App-master\
ode_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (F:\\project\\App-master\
ode_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (F:\\project\\App-master\
ode_modules\\which\\which.js:80:29)
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\which\\which.js:89:16
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\\project\\App-master\
ode_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (F:\\project\\App-master\
ode_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (F:\\project\\App-master\
ode_modules\\which\\which.js:80:29)
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\which\\which.js:89:16
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\
    at getNotFoundError (F:\\\\project\\\\App-master\\\
ode_modules\\\\which\\\\which.js:13:12)\
    at F (F:\\\\project\\\\App-master\\\
ode_modules\\\\which\\\\which.js:68:19)\
    at E (F:\\\\project\\\\App-master\\\
ode_modules\\\\which\\\\which.js:80:29)\
    at F:\\\\project\\\\App-master\\\
ode_modules\\\\which\\\\which.js:89:16\
    at F:\\\\project\\\\App-master\\\
ode_modules\\\\isexe\\\\index.js:42:5\
    at F:\\\\project\\\\App-master\\\
ode_modules\\\\isexe\\\\windows.js:36:5\
    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable \"python\" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\\project\\App-master\
ode_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (F:\\project\\App-master\
ode_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (F:\\project\\App-master\
ode_modules\\which\\which.js:80:29)
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\which\\which.js:89:16
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\\project\\App-master\
ode_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (F:\\project\\App-master\
ode_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (F:\\project\\App-master\
ode_modules\\which\\which.js:80:29)
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\which\\which.js:89:16
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at F:\\project\\App-master\
ode_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\
    at getNotFoundError (F:\\\\project\\\\App-master\\\
ode_modules\\\\which\\\\which.js:13:12)\
    at F (F:\\\\project\\\\App-master\\\
ode_modules\\\\which\\\\which.js:68:19)\
    at E (F:\\\\project\\\\App-master\\\
ode_modules\\\\which\\\\which.js:80:29)\
    at F:\\\\project\\\\App-master\\\
ode_modules\\\\which\\\\which.js:89:16\
    at F:\\\\project\\\\App-master\\\
ode_modules\\\\isexe\\\\index.js:42:5\
    at F:\\\\project\\\\App-master\\\
ode_modules\\\\isexe\\\\windows.js:36:5\
    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find \"python\". checking python launcher
gyp verb could not find \"python\". guessing location
gyp verb ensuring that file exists: C:\\Python27\\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (F:\\project\\App-master\
ode_modules\
ode-gyp\\lib\\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (F:\\project\\App-master\
ode_modules\
ode-gyp\\lib\\configure.js:508:16)
gyp ERR! stack     at F:\\project\\App-master\
ode_modules\\graceful-fs\\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\Program Files\\\
odejs\\\
ode.exe\" \"F:\\\\project\\\\App-master\\\
ode_modules\\\
ode-gyp\\\\bin\\\
ode-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
gyp ERR! cwd F:\\project\\App-master\
ode_modules\
ode-sass
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2

**$ npm install**
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN rm not removing F:\project\App-master\node_modules\.bin\uglifyjs.cmd as it wasn't installed by F:\project\App-master\node_modules\uglify-js
npm WARN rm not removing F:\project\App-master\node_modules\.bin\uglifyjs as it wasn't installed by F:\project\App-master\node_modules\uglify-js
npm WARN rm not removing F:\project\App-master\node_modules\.bin\semver.cmd as it wasn't installed by F:\project\App-master\node_modules\semver
npm WARN rm not removing F:\project\App-master\node_modules\.bin\semver as it wasn't installed by F:\project\App-master\node_modules\semver
npm WARN rm not removing F:\project\App-master\node_modules\detective\node_modules\.bin\acorn.cmd as it wasn't installed by F:\project\App-master\node_modules\detective\node_modules\acorn
npm WARN rm not removing F:\project\App-master\node_modules\detective\node_modules\.bin\acorn as it wasn't installed by F:\project\App-master\node_modules\detective\node_modules\acorn
npm WARN rm not removing F:\project\App-master\node_modules\.bin\acorn.cmd as it wasn't installed by F:\project\App-master\node_modules\acorn
npm WARN rm not removing F:\project\App-master\node_modules\.bin\acorn as it wasn't installed by F:\project\App-master\node_modules\acorn
npm WARN rm not removing F:\project\App-master\node_modules\@browserify\acorn5-object-spread\node_modules\.bin\acorn.cmd as it wasn't installed by F:\project\App-master\node_modules\@browserify\acorn5-object-spread\node_modules\acorn
npm WARN rm not removing F:\project\App-master\node_modules\@browserify\acorn5-object-spread\node_modules\.bin\acorn as it wasn't installed by F:\project\App-master\node_modules\@browserify\acorn5-object-spread\node_modules\acorn

> uws@9.14.0 install F:\project\App-master\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@3.13.1 install F:\project\App-master\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall F:\project\App-master\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe F:\project\App-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'F:\\project\\App-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\project\App-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\project\App-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\project\App-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\project\App-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\project\App-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\project\App-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (F:\project\App-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\project\App-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\project\App-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\project\App-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\project\App-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\project\App-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (F:\\project\\App-master\\node_modules\\which\\which.js:13:12)\n    at F (F:\\project\\App-master\\node_modules\\which\\which.js:68:19)\n    at E (F:\\project\\App-master\\node_modules\\which\\which.js:80:29)\n    at F:\\project\\App-master\\node_modules\\which\\which.js:89:16\n    at F:\\project\\App-master\\node_modules\\isexe\\index.js:42:5\n    at F:\\project\\App-master\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\project\App-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\project\App-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\project\App-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\project\App-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\project\App-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\project\App-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (F:\project\App-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (F:\project\App-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (F:\project\App-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at F:\project\App-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at F:\project\App-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at F:\project\App-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (F:\\project\\App-master\\node_modules\\which\\which.js:13:12)\n    at F (F:\\project\\App-master\\node_modules\\which\\which.js:68:19)\n    at E (F:\\project\\App-master\\node_modules\\which\\which.js:80:29)\n    at F:\\project\\App-master\\node_modules\\which\\which.js:89:16\n    at F:\\project\\App-master\\node_modules\\isexe\\index.js:42:5\n    at F:\\project\\App-master\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (F:\project\App-master\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (F:\project\App-master\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at F:\project\App-master\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\project\\App-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd F:\project\App-master\node_modules\node-sass
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\radhasoami\AppData\Roaming\npm-cache\_logs\2018-03-28T09_25_27_349Z-debug.log
```

**Comment by gocanto** [comment]
the front end is pretty old made. So, it works with `bower`.

therefore, you need to run `bower install`
